name: Deploy Task Tracker to Azure

on:
 push:
   branches:
    -main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   steps:
   -uses: actions/checkout@v4

   -name: Set up Python
   uses: actions/setup-python@v5
   with: 
    python-version '3.10'

   -name: Install dependencies
   run: |
      python -m pip install
      --upgrade pip
         pip install -r
       requirements.txt

-name: 'Deploy to Azure Web App'
uses: azure/webapps-deploy@v2
with:
 app-name:
  'app-task-tracker-hedayah'
 publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
